package org.uv.tpcsw_practica03.GUI;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.uv.tpcsw_practica03.DAODepartamento;
import org.uv.tpcsw_practica03.DAOEmpleado;
import org.uv.tpcsw_practica03.Departamento;

public class DepartamentosGUI extends javax.swing.JFrame {

    DAOEmpleado dao = new DAOEmpleado();
    DAODepartamento daoDepto = new DAODepartamento();
    DefaultTableModel model = new DefaultTableModel();
    
    public DepartamentosGUI() {
        initComponents();
        setLocationRelativeTo(this);
        deshabilitarCampos();
    }
    
    private void deshabilitarCampos() {
        txtNombre.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(false);
        txtClave.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnEliminar.setEnabled(false);
        jtDeptos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDeptos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnNuevoDepto = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscarTodo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarPorId = new javax.swing.JButton();
        btnBuscarPorId = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre: ");

        jtDeptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Clave", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDeptos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDeptosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDeptos);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel6.setText("Departamentos");

        btnNuevoDepto.setText("Nuevo depto");
        btnNuevoDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDeptoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscarTodo.setText("Buscar todo");
        btnBuscarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTodoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("¿Qué acción desea realizar?");

        btnEliminarPorId.setText("Eliminar por id");
        btnEliminarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPorIdActionPerformed(evt);
            }
        });

        btnBuscarPorId.setText("Buscar por id");
        btnBuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorIdActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("Clave:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnActualizar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoDepto)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarPorId)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarPorId)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarTodo)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoDepto)
                    .addComponent(btnBuscarPorId)
                    .addComponent(btnEliminarPorId)
                    .addComponent(btnBuscarTodo))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDeptoActionPerformed

    txtNombre.setEnabled(true);
    btnGuardar.setEnabled(true);
    btnActualizar.setEnabled(true);
    txtClave.setEnabled(false);
    btnBuscar.setEnabled(false);
    btnEliminar.setEnabled(false);
       
    }//GEN-LAST:event_btnNuevoDeptoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Departamento depto = new Departamento();
        depto.setClave(Long.valueOf(txtClave.getText()));
        depto.setNombre(txtNombre.getText());
        if(daoDepto.save(depto)) {
            JOptionPane.showMessageDialog(null, "Departamento guardado con éxito");
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar departamento");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        Long clave = Long.valueOf(txtClave.getText());
        
        Departamento depto = new Departamento();
        depto.setClave(clave);
        depto.setNombre(txtNombre.getText());
        
        if(daoDepto.update(depto, clave)) {
            JOptionPane.showMessageDialog(null, "Departamento actualizado con éxito");
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar departamento");
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        Long id = Long.valueOf(txtClave.getText());
        
        if(daoDepto.delete(id)) {
            JOptionPane.showMessageDialog(null, "Departamento eliminado con éxito");
        } else {
            JOptionPane.showMessageDialog(null, "Error al elminar departamento");
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTodoActionPerformed

        List<Departamento> deptos = daoDepto.findAll();
        
        model.addColumn("Clave");
        model.addColumn("Nombre");
        
        if(deptos != null){ 
            for (Departamento depto : deptos) {
                model.addRow(
                        new Object[]{
                            depto.getClave(), 
                            depto.getNombre(), 
                        });
            }
        }

        jtDeptos.setModel(model);
    }//GEN-LAST:event_btnBuscarTodoActionPerformed

    private void btnEliminarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPorIdActionPerformed
        txtNombre.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(false);
        txtClave.setEnabled(true);
        btnBuscar.setEnabled(false);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnEliminarPorIdActionPerformed

    private void btnBuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorIdActionPerformed

        txtNombre.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(false);
        txtClave.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnEliminar.setEnabled(false);
        
    }//GEN-LAST:event_btnBuscarPorIdActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Departamento depto = daoDepto.findById(Long.valueOf(txtClave.getText()));
        
        txtClave.setText(String.valueOf(depto.getClave()));
        txtNombre.setText(depto.getNombre());
        
        model.addColumn("Clave");
        model.addColumn("Nombre");
        
        model.addRow(
                new Object[]{
                    depto.getClave(), 
                    depto.getNombre(), 
                });
        
        jtDeptos.setModel(model);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jtDeptosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDeptosMouseClicked
        
        int fila = jtDeptos.getSelectedRow();
        
        long clave = (long) jtDeptos.getValueAt(fila, 0);
        String nombre = (String) jtDeptos.getValueAt(fila, 1);
       
        txtClave.setText(String.valueOf(clave));
        txtNombre.setText(nombre);
       
        
        
    }//GEN-LAST:event_jtDeptosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarPorId;
    private javax.swing.JButton btnBuscarTodo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarPorId;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoDepto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtDeptos;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
